FreeBSD backend
ximion/appstream-generator pull request #113
Opened 2023-04-20 18:35 UTC by arrowd

2023-04-27 23:43 UTC, ximion commented
> Some Linux distributions as well as FreeBSD OS install 3rd party software into
a prefix that differs from "/usr". This change makes asgen work in such cases.

Can you elaborate on that? Installing metadata into any location outside of `/usr/(local)/share/metainfo` is not permitted and not supported by any other tool, so I would really not like to make an exception here...

2023-04-27 23:48 UTC, ximion commented
Also, by changing this you would not catch all system software that apparently is installed in `/usr`, *and* by making this a global build-time flag you can not process data for any other system other than FreeBSD correctly. So you can't use `appstream-generator` on FreeBSD to process a Debian or Arch Linux archive (or vice versa).

2023-04-28 06:07 UTC, arrowd commented
> Can you elaborate on that?

FreeBSD installs 3rdpart software into `/usr/local`. Some Linuxes, AFAIK, install stuff into `/opt`.

> Also, by changing this you would not catch all system software that apparently is installed in /usr

I was under assumption that there could be no system software that have AppStream metadata. At least there are no in FreeBSD. But this point is valid.

> and by making this a global build-time flag you can not process data for any other system other than FreeBSD correctly. So you can't use appstream-generator on FreeBSD to process a Debian or Arch Linux archive (or vice versa).

I didn't even think about such use case. Yes, this is a valid point too.

I'm happy to fix this, but how? For FreeBSD backend to work I need asgen to use `/usr/local` prefix everywhere and without the first commit of this PR it is not possible.

2023-05-14 18:54 UTC, ximion commented
> FreeBSD installs 3rdpart software into `/usr/local`. Some Linuxes, AFAIK, install stuff into `/opt`.

But do FreeBSD *packages* also contain stuff in `/usr/local`?
`/opt` is not a supported location at all for AppStream metadata, `/usr/local/share/metainfo` is fairly uncommon for packaged stuff, but that location is at least read, so we could potentially also support it.

2023-05-22 07:10 UTC, arrowd commented
Bump. Can we get this in?

2023-05-29 16:01 UTC, ximion requested changes
Just a tiny nitpick about the TODO entry in the code, and the general disclaimer that I can't really test the code.
But apart from that, this looks good to go (I'd just like some feedback if the todo item is addressed, merging new code with that is a bit odd).

The patch also needs a (likely very simple) rebase on the master branch :-)

2023-05-29 16:53 UTC, arrowd commented on src/asgen/backends/freebsd/fbsdpkg.d
> +        pkgFname = buildPath (pkgRoot, pkgjson["path"].str()); // TODO: or pkgjson["repopath"] ???
@bapt Can you help me here? I'm parsing packagesite lines in this code and using "path" entry to get "All/package-name-1.2.3.pkg" portion of the filename. The "repopath" entry contains the same value in the metadata from the official FreeBSD cluster. What's the difference and what's more correct to use there?

2023-05-29 16:54 UTC, arrowd commented
> Just a tiny nitpick about the TODO entry in the code, and the general disclaimer that I can't really test the code.

We're running it for about a month now, so it works for us.

2023-06-05 07:29 UTC, bapt commented on src/asgen/backends/freebsd/fbsdpkg.d
> +        pkgFname = buildPath (pkgRoot, pkgjson["path"].str()); // TODO: or pkgjson["repopath"] ???
if I understand correctly what you are asking for, repopath is the path entry of the packagesite lines.

2023-06-05 11:28 UTC, ximion commented
> We're running it for about a month now, so it works for us.

That's good enough - if the conflicts of this PR with the master branch are resolved, we can merge this (and maybe even remove the TODO, since it obviously works).

2023-06-06 07:28 UTC, arrowd commented
This should be ready to get in now.

2023-06-06 08:05 UTC, ximion approved these changes

2023-06-06 08:47 UTC, ximion commented
> This should be ready to get in now.

It is indeed! Thank you for your patch and your patience!

2023-06-06 08:47 UTC, merged