utils: guard mkdir call with std.file.exists
ximion/appstream-generator pull request #114
Opened 2023-04-23 22:53 UTC by pabloyoyoista

Fixes the following stack trace:

2023-04-23 21:02:16 - INFO: Exporting data for v3.15 (main/aarch64) 2023-04-23 21:02:16std.file.FileException@/usr/include/d/std/file.d(2972): /home/abuild/cache/export/media/v3.15/g/gv/gvim.desktop/4016a69fc2135fa29a3414b2c8bd20d9//icons: File exists ----------------
??:? @trusted bool std.file.cenforce!(bool).cenforce(bool, scope const(char)[], scope const(char)*, immutable(char)[], ulong) [0x563624998170] ??:? @safe void std.file.mkdir!(immutable(char)[]).mkdir(immutable(char)[]) [0x563624a439d0] ??:? @trusted void asgen.utils.copyDir(in immutable(char)[], in immutable(char)[], bool) [0x563624a43500] ??:? /usr/bin/appstream-generator [0x5636249e2190] ??:? void std.parallelism.ParallelForeach!(asgen.backends.interfaces.Package[]).ParallelForeach.opApply(scope int delegate(ref asgen.backends.interfaces.Package)).doIt() [0x5636249e8f30] ??:? void std.parallelism.TaskPool.executeWorkLoop() [0x7fd515e4efe0] ??:? thread_entryPoint [0x7fd515b9d5b0]
 - DEBUG: Building final metadata and hints files.

This occurred once during debugging, but haven't tested this in-depth. Anyway, looking at the code seems sort of obvious fix.

2023-04-23 23:15 UTC, nekopsykose commented
isn't this still liable to TOCTOU in the exact same way? it's better to catch the FileException or something instead and check what it is (though i'm not sure it disambiguates 'what exception')

2023-04-23 23:18 UTC, nekopsykose commented
or maybe there's an api better than that 'mkdir' that can just pass if it already exists

2023-04-23 23:19 UTC, nekopsykose commented
(the toctou here is something can make the dir between when you check it and when you mkdir it, which would crash the same way, just much more rare)

2023-04-23 23:55 UTC, ximion commented
> or maybe there's an api better than that 'mkdir' that can just pass if it already exists

Yes, I would prefer if `mkdirRecurse` was used here for exactly this reason :-) https://dlang.org/phobos/std_file.html#.mkdirRecurse

2023-04-23 23:55 UTC, ximion requested changes
> or maybe there's an api better than that 'mkdir' that can just pass if it already exists

Yes, I would prefer if `mkdirRecurse` was used here for exactly this reason :-) https://dlang.org/phobos/std_file.html#.mkdirRecurse

2023-04-23 23:59 UTC, pabloyoyoista commented
Sure, thank you both! I am pretty lost with D

2023-04-24 01:58 UTC, nekopsykose commented
you should update the commit message too

2023-04-24 15:19 UTC, pabloyoyoista commented
Done!

2023-04-24 15:20 UTC, ximion approved these changes
Thanks! :-D

2023-04-24 15:20 UTC, merged